### ISSUE TITLE
Bug in test

### ISSUE THREAD

**Issue by ruinianxu** [zysszy/TreeGen-Pytorch#1]
Hi @zysszy , 

There is a bug when running ```python3 run.py test 1``` cuz there is no definition for the function of pre. I attached the error message below. Thanks.

```
Traceback (most recent call last):
  File "run.py", line 465, in <module>
    test()
  File "run.py", line 422, in test
    pre()
NameError: name 'pre' is not defined
```

**Comment by zysszy** [comment]
I am sorry for that. 

I have fixed this bug by deleting this buggy line.

Thanks~

Zeyu
